name: as_hqmags
channels:
  - conda-forge
  - bioconda
dependencies:
  - jupyterlab
  - jupytext
  - seaborn
  - pandas
  - pysqlite3
  - openpyxl
  - r-base
  - r-essentials
  - r-tidyverse
  - r-argparser
  - bioconductor-genomicranges
  - r-pbapply
  - r-irkernel
  - alive-progress
  - pip
  - pip:
      - azure-cli