# This file should contain everything to configure the workflow on a global scale.

#### PROJECT INFORMATION ####
# This section control your project configuration. 
# Each project are separated by "-". 
# A project must contain the variable "name" and "samples".
# - name : name of your project
# - samples : a csv file containing a list of genome ids for analysis with multiple sources mentioned. Genome ids must be unique.
# - prokka-db (optional): list of the custom accessions to use as prokka reference database
# - gtdb-tax (optional): output summary file of GTDB-tk with "user_genome" and "classification" as the two minimum columns

projects:
# Project 8
  - name: p__Nitrospirota_all
    samples: config/p__Nitrospirota_all/p__Nitrospirota_all.csv
    gtdb-tax: config/wwtphqmags/wwtphqmags.gtdbtk.summary.tsv
# Project 9
  - name: p__Myxococcota_all
    samples: config/p__Myxococcota_all/p__Myxococcota_all.csv
    gtdb-tax: config/wwtphqmags/wwtphqmags.gtdbtk.summary.tsv


#### RULE CONFIGURATION ####
# rules: set value to TRUE if you want to run the analysis or FALSE if you don't
rules:
  seqfu: FALSE
  mlst: FALSE
  refseq_masher: FALSE
  checkm: False
  prokka-gbk: FALSE
  antismash-summary: True
  antismash-zip: FALSE
  query_bigslice: FALSE
  bigscape: FALSE
  bigslice: FALSE
  automlst_wrapper: FALSE
  arts: FALSE
  roary: FALSE
  eggnog: FALSE
  eggnog-roary: FALSE
  # other parameter settings
  rnammer: FALSE


#### RESOURCES CONFIGURATION ####
# resources : the location of the resources to run the rule.
# The default location is at "resources/{resource_name}".
resources_path: 
  antismash_db: resources/antismash_db
  eggnog_db: resources/eggnog_db
  BiG-SCAPE: resources/BiG-SCAPE
  bigslice: resources/bigslice
  checkm: resources/checkm
  #RNAmmer: resources/RNAmmer # Path must be specified if rule configuration "rnammer" is TRUE