#' Imports BiG-SCAPE's info from clustering files
#'
#' @param bigscape_dir Directory with bigscape output
#'
#' @return A tibble in "wide format" with BGC ids , its classes, cutoffs and GCFs

import_bigscape <- function(bigscape_dir){
  
  clustering_files <- 
    list.files(
      path = bigscape_dir,
      pattern = "clustering",
      recursive = TRUE, 
      full.names = TRUE) 
  
  sapply(clustering_files, 
         read_tsv, 
         col_types = 'cc', 
         simplify = FALSE) %>%
    set_names(basename(clustering_files)) %>%
    bind_rows(.id = "table") %>%
    mutate(cutoff = as.numeric(str_match(table, "clustering_c(.+)\\.tsv")[,2]), 
           class = str_match(table, "(^.+?)_clustering")[,2]) %>%
    select(-table) %>%
    set_names(c('bgc_id', 'GCF', 'cutoff', 'class')) %>%
    distinct() %>%
    pivot_wider(values_from = GCF, names_from = cutoff, names_prefix = "GCF_c")
  
}  

bigscape_classes <- c("Terpene",
                      "RiPPs", 
                      "NRPS",
                      "PKS-NRP_Hybrids",
                      "PKSI",
                      "PKSother", 
                      "Saccharides",
                      "Others")                             

my_classes <- c("Terpene", 
                "RiPP", 
                "NRPS", 
                "NRPS-PKS", 
                "PKS", 
                "PKS", 
                "Other", 
                "Other")

my_palettes <- c("Oranges",
               "Greens",
               "Reds",
               "Purples",
               "Blues",
               "Greys")

#' Translates BGC class in BiG-SCAPE notation to a customized notation
#'
#' @param bigscape_class BiG-SCAPE class
#'
#' @return Custom class
translate_class <- Vectorize(function(bigscape_class){
  my_classes[match(bigscape_class, bigscape_classes)]
})


my_colors <- map_chr(my_palettes, ~brewer.pal(7, .x)[5])

#' Finds GCFs containing MIBiG BGCs, starting with the string BGC
#' #'
#' @param bigscape_df Dataframe, generated by import_bigscape
#' @param cutoff Cutoff value
#'
#' @return 
find_mibig_hits <- function(bigscape_df, cutoff = 0.3){
  bigscape_df %>%
    select(bgc_id, ends_with(as.character(cutoff))) %>%
    filter(str_detect(bgc_id, "^BGC\\d{7}\\.1")) %>%
    select(starts_with('GCF')) %>%
    pull()
}

#' Imports BiG-SCAPE's network files
#'
#' @param bigscape_dir Directory with bigscape output
#'
#' @return A tibble in with edges
#' 
import_networks <- function(bigscape_dir, cutoff = 0.3){
  
  pattern <- paste0(
    "_c",
    format(round(cutoff, 2), nsmall = 2),
    ".network$")
  
  network_files <- 
    list.files(
      path = bigscape_dir,
      pattern = pattern,
      recursive = TRUE, 
      full.names = TRUE) 
  
  sapply(network_files, 
         read_tsv, 
         col_select = 1:4,
         col_types = 'ccdd', 
         simplify = FALSE) %>%
    set_names(basename(network_files)) %>%
    bind_rows(.id = "table") %>%
    mutate(cutoff = as.numeric(str_match(table, "_c(.+)\\.network")[,2]), 
           class = str_match(table, "(^.+?)_c")[,2]) %>%
    select(-table) %>%
    set_names(c('bgc_id_1', 'bgc_id_2', 'raw_distance', 'squared_similarity', 'cutoff', 'class')) %>%
    distinct()
}

                     